/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.TablapapeleriaJpaController;
import controlador.exceptions.NonexistentEntityException;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Tablapapeleria;

/**
 *
 * @author javie
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
Color morado = new Color(208, 204, 252);

    public frmMenuPrincipal() {
        initComponents();
        this.getContentPane().setBackground(morado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmNuevoProducto = new javax.swing.JFrame();
        lblNuevoCodigo = new javax.swing.JLabel();
        lblNuevoProducto = new javax.swing.JLabel();
        lblNuevoFamilia = new javax.swing.JLabel();
        lblNuevoPrecio = new javax.swing.JLabel();
        txtNuevoCodigo = new javax.swing.JTextField();
        txtNuevoProducto = new javax.swing.JTextField();
        txtNuevoFamilia = new javax.swing.JTextField();
        txtNuevoPrecio = new javax.swing.JTextField();
        lblNuevoRellena = new javax.swing.JLabel();
        btnNuevoNuevoProducto = new javax.swing.JButton();
        btnNuevoReset = new javax.swing.JButton();
        frmModificarProducto = new javax.swing.JFrame();
        lblModificarCodigo = new javax.swing.JLabel();
        lblModificarProducto = new javax.swing.JLabel();
        lblModificarFamilia = new javax.swing.JLabel();
        lblModificarPrecio = new javax.swing.JLabel();
        txtModificarCodigo = new javax.swing.JTextField();
        txtModificarProducto = new javax.swing.JTextField();
        txtModificarFamilia = new javax.swing.JTextField();
        txtModificarPrecio = new javax.swing.JTextField();
        lblModificarRellena = new javax.swing.JLabel();
        btnModificarModificarProducto = new javax.swing.JButton();
        btnModificarReset = new javax.swing.JButton();
        btnModificarBuscar = new javax.swing.JButton();
        frmListarProducto = new javax.swing.JFrame();
        btnListarListar = new javax.swing.JButton();
        scpListarTabla = new javax.swing.JScrollPane();
        tblListarProductos = new javax.swing.JTable();
        btnListarReporte = new javax.swing.JButton();
        frmBuscarProducto = new javax.swing.JFrame();
        btnBuscarBuscar = new javax.swing.JButton();
        scpBuscarTabla = new javax.swing.JScrollPane();
        tblBuscarProductos = new javax.swing.JTable();
        lblBuscarCodigo = new javax.swing.JLabel();
        txtBuscarCodigo = new javax.swing.JTextField();
        frmBorrarProducto = new javax.swing.JFrame();
        lblBorrarCodigo = new javax.swing.JLabel();
        lblBorrarProducto = new javax.swing.JLabel();
        lblBorrarFamilia = new javax.swing.JLabel();
        lblBorrarPrecio = new javax.swing.JLabel();
        txtBorrarCodigo = new javax.swing.JTextField();
        txtBorrarProducto = new javax.swing.JTextField();
        txtBorrarFamilia = new javax.swing.JTextField();
        txtBorrarPrecio = new javax.swing.JTextField();
        lblBorrarRellena = new javax.swing.JLabel();
        btnBorrarBorrarProducto = new javax.swing.JButton();
        btnBorrarReset = new javax.swing.JButton();
        btnBorrarBuscar = new javax.swing.JButton();
        btnNuevoProducto = new javax.swing.JButton();
        btnModificarProducto = new javax.swing.JButton();
        btnListarProducto = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();

        frmNuevoProducto.setTitle("Nuevo producto");
        frmNuevoProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        frmNuevoProducto.setSize(new java.awt.Dimension(400, 350));

        lblNuevoCodigo.setText("Código");

        lblNuevoProducto.setText("Producto");

        lblNuevoFamilia.setText("Familia");

        lblNuevoPrecio.setText("Precio");

        txtNuevoCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtNuevoProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtNuevoFamilia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtNuevoPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNuevoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoPrecioActionPerformed(evt);
            }
        });

        lblNuevoRellena.setText("Rellena todos los campos y pulsa 'Nuevo producto'.");
        lblNuevoRellena.setEnabled(false);

        btnNuevoNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Add.png"))); // NOI18N
        btnNuevoNuevoProducto.setText("Nuevo producto");
        btnNuevoNuevoProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoNuevoProductoActionPerformed(evt);
            }
        });

        btnNuevoReset.setText("Reset");
        btnNuevoReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmNuevoProductoLayout = new javax.swing.GroupLayout(frmNuevoProducto.getContentPane());
        frmNuevoProducto.getContentPane().setLayout(frmNuevoProductoLayout);
        frmNuevoProductoLayout.setHorizontalGroup(
            frmNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmNuevoProductoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(frmNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frmNuevoProductoLayout.createSequentialGroup()
                            .addComponent(btnNuevoNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevoReset, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frmNuevoProductoLayout.createSequentialGroup()
                            .addGroup(frmNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNuevoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNuevoFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNuevoCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNuevoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(frmNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNuevoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNuevoFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblNuevoRellena))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        frmNuevoProductoLayout.setVerticalGroup(
            frmNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmNuevoProductoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(frmNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoCodigo)
                    .addComponent(txtNuevoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frmNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoProducto)
                    .addComponent(txtNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frmNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoFamilia)
                    .addComponent(txtNuevoFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(frmNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoPrecio)
                    .addComponent(txtNuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblNuevoRellena)
                .addGap(37, 37, 37)
                .addGroup(frmNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevoReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoNuevoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        frmModificarProducto.setTitle("Modificar producto");
        frmModificarProducto.setSize(new java.awt.Dimension(400, 350));

        lblModificarCodigo.setText("Código");

        lblModificarProducto.setText("Producto");
        lblModificarProducto.setEnabled(false);

        lblModificarFamilia.setText("Familia");
        lblModificarFamilia.setEnabled(false);

        lblModificarPrecio.setText("Precio");
        lblModificarPrecio.setEnabled(false);

        txtModificarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarCodigoActionPerformed(evt);
            }
        });

        txtModificarProducto.setEnabled(false);

        txtModificarFamilia.setEnabled(false);

        txtModificarPrecio.setEnabled(false);

        lblModificarRellena.setText("Ingresa el código del producto a modificar");
        lblModificarRellena.setEnabled(false);

        btnModificarModificarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Modify.png"))); // NOI18N
        btnModificarModificarProducto.setText("Modificar producto");
        btnModificarModificarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarModificarProductoActionPerformed(evt);
            }
        });

        btnModificarReset.setText("Reset");
        btnModificarReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarResetActionPerformed(evt);
            }
        });

        btnModificarBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Search.png"))); // NOI18N
        btnModificarBuscar.setText("Buscar");
        btnModificarBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmModificarProductoLayout = new javax.swing.GroupLayout(frmModificarProducto.getContentPane());
        frmModificarProducto.getContentPane().setLayout(frmModificarProductoLayout);
        frmModificarProductoLayout.setHorizontalGroup(
            frmModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmModificarProductoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(frmModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificarModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frmModificarProductoLayout.createSequentialGroup()
                        .addGroup(frmModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblModificarProducto)
                            .addComponent(lblModificarFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModificarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModificarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frmModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModificarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModificarFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frmModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frmModificarProductoLayout.createSequentialGroup()
                                    .addComponent(txtModificarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModificarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frmModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnModificarReset, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lblModificarRellena))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        frmModificarProductoLayout.setVerticalGroup(
            frmModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmModificarProductoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(frmModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModificarCodigo)
                    .addComponent(txtModificarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frmModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModificarProducto)
                    .addComponent(txtModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frmModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModificarFamilia)
                    .addComponent(txtModificarFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(frmModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModificarPrecio)
                    .addComponent(txtModificarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblModificarRellena)
                .addGap(37, 37, 37)
                .addGroup(frmModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarModificarProducto)
                    .addComponent(btnModificarReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        frmListarProducto.setTitle("Listar productos");
        frmListarProducto.setSize(new java.awt.Dimension(400, 350));

        btnListarListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Line Chart.png"))); // NOI18N
        btnListarListar.setText("Listar productos");
        btnListarListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarListarActionPerformed(evt);
            }
        });

        tblListarProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Producto", "Familia", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scpListarTabla.setViewportView(tblListarProductos);

        btnListarReporte.setText("Generar reporte");
        btnListarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmListarProductoLayout = new javax.swing.GroupLayout(frmListarProducto.getContentPane());
        frmListarProducto.getContentPane().setLayout(frmListarProductoLayout);
        frmListarProductoLayout.setHorizontalGroup(
            frmListarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpListarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmListarProductoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnListarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListarListar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        frmListarProductoLayout.setVerticalGroup(
            frmListarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmListarProductoLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(frmListarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarListar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpListarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        frmBuscarProducto.setTitle("Listar productos");
        frmBuscarProducto.setSize(new java.awt.Dimension(400, 300));

        btnBuscarBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Search.png"))); // NOI18N
        btnBuscarBuscar.setText("Buscar productos");
        btnBuscarBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBuscarActionPerformed(evt);
            }
        });

        tblBuscarProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Producto", "Familia", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scpBuscarTabla.setViewportView(tblBuscarProductos);

        lblBuscarCodigo.setText("Código:");

        txtBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmBuscarProductoLayout = new javax.swing.GroupLayout(frmBuscarProducto.getContentPane());
        frmBuscarProducto.getContentPane().setLayout(frmBuscarProductoLayout);
        frmBuscarProductoLayout.setHorizontalGroup(
            frmBuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpBuscarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmBuscarProductoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblBuscarCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        frmBuscarProductoLayout.setVerticalGroup(
            frmBuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmBuscarProductoLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(frmBuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscarCodigo)
                    .addComponent(txtBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpBuscarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        frmBorrarProducto.setTitle("Modificar producto");
        frmBorrarProducto.setSize(new java.awt.Dimension(400, 350));

        lblBorrarCodigo.setText("Código");

        lblBorrarProducto.setText("Producto");
        lblBorrarProducto.setEnabled(false);

        lblBorrarFamilia.setText("Familia");
        lblBorrarFamilia.setEnabled(false);

        lblBorrarPrecio.setText("Precio");
        lblBorrarPrecio.setEnabled(false);

        txtBorrarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBorrarCodigoActionPerformed(evt);
            }
        });

        txtBorrarProducto.setEnabled(false);

        txtBorrarFamilia.setEnabled(false);

        txtBorrarPrecio.setEnabled(false);

        lblBorrarRellena.setText("Ingresa el código del producto a eliminar");
        lblBorrarRellena.setEnabled(false);

        btnBorrarBorrarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Delete.png"))); // NOI18N
        btnBorrarBorrarProducto.setText("Eliminar producto");
        btnBorrarBorrarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarBorrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarBorrarProductoActionPerformed(evt);
            }
        });

        btnBorrarReset.setText("Reset");
        btnBorrarReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarResetActionPerformed(evt);
            }
        });

        btnBorrarBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Search.png"))); // NOI18N
        btnBorrarBuscar.setText("Buscar");
        btnBorrarBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmBorrarProductoLayout = new javax.swing.GroupLayout(frmBorrarProducto.getContentPane());
        frmBorrarProducto.getContentPane().setLayout(frmBorrarProductoLayout);
        frmBorrarProductoLayout.setHorizontalGroup(
            frmBorrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmBorrarProductoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(frmBorrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBorrarBorrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frmBorrarProductoLayout.createSequentialGroup()
                        .addGroup(frmBorrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBorrarProducto)
                            .addComponent(lblBorrarFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBorrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBorrarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frmBorrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBorrarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBorrarFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frmBorrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frmBorrarProductoLayout.createSequentialGroup()
                                    .addComponent(txtBorrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBorrarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frmBorrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBorrarReset, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBorrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lblBorrarRellena))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        frmBorrarProductoLayout.setVerticalGroup(
            frmBorrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmBorrarProductoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(frmBorrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBorrarCodigo)
                    .addComponent(txtBorrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frmBorrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBorrarProducto)
                    .addComponent(txtBorrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frmBorrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBorrarFamilia)
                    .addComponent(txtBorrarFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(frmBorrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBorrarPrecio)
                    .addComponent(txtBorrarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblBorrarRellena)
                .addGap(37, 37, 37)
                .addGroup(frmBorrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarBorrarProducto)
                    .addComponent(btnBorrarReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú inicio");
        setSize(new java.awt.Dimension(400, 500));

        btnNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Add.png"))); // NOI18N
        btnNuevoProducto.setText("Nuevo producto");
        btnNuevoProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoProducto.setFocusPainted(false);
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });

        btnModificarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Modify.png"))); // NOI18N
        btnModificarProducto.setText("Modificar producto");
        btnModificarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarProducto.setFocusPainted(false);
        btnModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProductoActionPerformed(evt);
            }
        });

        btnListarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Line Chart.png"))); // NOI18N
        btnListarProducto.setText("Listar producto");
        btnListarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarProducto.setFocusPainted(false);
        btnListarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProductoActionPerformed(evt);
            }
        });

        btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Search.png"))); // NOI18N
        btnBuscarProducto.setText("Buscar producto");
        btnBuscarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarProducto.setFocusPainted(false);
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Delete.png"))); // NOI18N
        btnEliminarProducto.setText("Eliminar producto");
        btnEliminarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarProducto.setFocusPainted(false);
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnNuevoProducto)
                .addGap(18, 18, 18)
                .addComponent(btnModificarProducto)
                .addGap(18, 18, 18)
                .addComponent(btnListarProducto)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarProducto)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarProducto)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        // TODO add your handling code here:
        frmNuevoProducto.setVisible(true);
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void btnModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProductoActionPerformed
        // TODO add your handling code here:
        frmModificarProducto.setVisible(true);
    }//GEN-LAST:event_btnModificarProductoActionPerformed

    private void btnListarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProductoActionPerformed
        // TODO add your handling code here:
        frmListarProducto.setVisible(true);
    }//GEN-LAST:event_btnListarProductoActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        // TODO add your handling code here:
        frmBuscarProducto.setVisible(true);
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        // TODO add your handling code here:
        frmBorrarProducto.setVisible(true);
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    //Para listar los productos
    private void btnListarListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarListarActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf= Persistence.createEntityManagerFactory("persistence");
        
        TablapapeleriaJpaController em=new TablapapeleriaJpaController(emf);
        
        List<Tablapapeleria> lista=em.findTablapapeleriaEntities();
        
        String nombres[] = {"ID", "Codigo", "Producto", "Familia", "Precio"};
        
        Object rowData[][] = new Object[lista.size()][5];
        int i = 0;

        for (Tablapapeleria a: lista){
            rowData[i][0] = a.getId();
            rowData[i][1] = a.getCodigo();
            rowData[i][2] = a.getProducto();
            rowData[i][3] = a.getFamilia();
            rowData[i][4] = a.getPrecio();
            i++;
        }
        DefaultTableModel tablem= new DefaultTableModel(rowData,nombres);

        tblListarProductos.setModel(tablem);
    }//GEN-LAST:event_btnListarListarActionPerformed

    private void btnNuevoResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoResetActionPerformed
        // TODO add your handling code here:
        txtNuevoCodigo.setText("");
        txtNuevoProducto.setText("");
        txtNuevoFamilia.setText("");
        txtNuevoPrecio.setText("");
    }//GEN-LAST:event_btnNuevoResetActionPerformed

    private void btnModificarResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarResetActionPerformed
        // TODO add your handling code here:
        txtModificarCodigo.setText("");
    }//GEN-LAST:event_btnModificarResetActionPerformed

    private void btnBorrarResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarResetActionPerformed
        // TODO add your handling code here:
        txtBorrarCodigo.setText("");
    }//GEN-LAST:event_btnBorrarResetActionPerformed

    //Para crear un nuevo producto
    private void btnNuevoNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoNuevoProductoActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf= Persistence.createEntityManagerFactory("persistence");
        
        TablapapeleriaJpaController em=new TablapapeleriaJpaController(emf);
        
        Tablapapeleria t=new Tablapapeleria(txtNuevoCodigo.getText(),txtNuevoProducto.getText(),txtNuevoFamilia.getText(),Double.valueOf(txtNuevoPrecio.getText()));
        
        em.create(t);
        
        btnNuevoResetActionPerformed(evt);
        frmNuevoProducto.dispose();
    }//GEN-LAST:event_btnNuevoNuevoProductoActionPerformed

    //Para buscar productos con un código
    private void btnBuscarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBuscarActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf= Persistence.createEntityManagerFactory("persistence");
        
        TablapapeleriaJpaController em=new TablapapeleriaJpaController(emf);
        
        List<Tablapapeleria> lista=em.findTablapapeleriaCodigo(txtBuscarCodigo.getText());
        
        String nombres[] = {"ID", "Codigo", "Producto", "Familia", "Precio"};
        
        Object rowData[][] = new Object[lista.size()][5];
        int i = 0;

        for (Tablapapeleria a: lista){
            rowData[i][0] = a.getId();
            rowData[i][1] = a.getCodigo();
            rowData[i][2] = a.getProducto();
            rowData[i][3] = a.getFamilia();
            rowData[i][4] = a.getPrecio();
            i++;
        }
        DefaultTableModel tablem= new DefaultTableModel(rowData,nombres);

        tblBuscarProductos.setModel(tablem);
    }//GEN-LAST:event_btnBuscarBuscarActionPerformed

    private void txtBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarCodigoActionPerformed
        // TODO add your handling code here:
        btnBuscarBuscarActionPerformed(evt);
    }//GEN-LAST:event_txtBuscarCodigoActionPerformed

    private void txtNuevoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoPrecioActionPerformed
        // TODO add your handling code here:
        btnNuevoNuevoProductoActionPerformed(evt);
    }//GEN-LAST:event_txtNuevoPrecioActionPerformed

    //Para buscar dende la ventana de modificar
    private void btnModificarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarBuscarActionPerformed
        // TODO add your handling code here:
        frmModificarProducto.dispose();
        frmBuscarProducto.setVisible(true);
        txtBuscarCodigo.setText(txtModificarCodigo.getText());
        txtModificarCodigo.setText("");
        btnBuscarBuscarActionPerformed(evt);
        txtBuscarCodigo.setText("");
    }//GEN-LAST:event_btnModificarBuscarActionPerformed
    
    //Para buscar desde la ventana de borrar
    private void btnBorrarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarBuscarActionPerformed
        // TODO add your handling code here:
        frmBorrarProducto.dispose();
        frmBuscarProducto.setVisible(true);
        txtBuscarCodigo.setText(txtBorrarCodigo.getText());
        txtBorrarCodigo.setText("");
        btnBuscarBuscarActionPerformed(evt);
        txtBuscarCodigo.setText("");
    }//GEN-LAST:event_btnBorrarBuscarActionPerformed

    //Para modificar un producto
    private void btnModificarModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarModificarProductoActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf= Persistence.createEntityManagerFactory("persistence");
        
        TablapapeleriaJpaController em=new TablapapeleriaJpaController(emf);
        
        if(!em.findTablapapeleriaCodigo(txtModificarCodigo.getText()).isEmpty()){
            Tablapapeleria producto=em.findTablapapeleriaCodigo(txtModificarCodigo.getText()).get(0);
            String nuevoCodigo=JOptionPane.showInputDialog("Introduce el nuevo código");
            if(nuevoCodigo!=null & !(nuevoCodigo.equals(""))){
                producto.setCodigo(nuevoCodigo);
                try {
                    em.edit(producto);
                } catch (Exception ex) {
                    Logger.getLogger(frmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            ventanaNoExiste(txtModificarCodigo.getText());
        }
        
        btnModificarResetActionPerformed(evt);
        frmModificarProducto.dispose();
    }//GEN-LAST:event_btnModificarModificarProductoActionPerformed

    //Para borrar un producto
    private void btnBorrarBorrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarBorrarProductoActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf= Persistence.createEntityManagerFactory("persistence");
        
        TablapapeleriaJpaController em=new TablapapeleriaJpaController(emf);
        
        if(!em.findTablapapeleriaCodigo(txtBorrarCodigo.getText()).isEmpty()){
            try {
                em.destroy(em.findTablapapeleriaCodigo(txtBorrarCodigo.getText()).get(0).getId());
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(frmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            ventanaNoExiste(txtBorrarCodigo.getText());
        }
        
        btnBorrarResetActionPerformed(evt);
        frmBorrarProducto.dispose();
       
    }//GEN-LAST:event_btnBorrarBorrarProductoActionPerformed

    private void txtBorrarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBorrarCodigoActionPerformed

        btnBorrarBorrarProductoActionPerformed(evt);
    }//GEN-LAST:event_txtBorrarCodigoActionPerformed

    private void txtModificarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarCodigoActionPerformed

        btnModificarModificarProductoActionPerformed(evt);
    }//GEN-LAST:event_txtModificarCodigoActionPerformed

    private void btnListarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarReporteActionPerformed
        EntityManagerFactory emf=Persistence.createEntityManagerFactory("persistence");
        TablapapeleriaJpaController controller=new TablapapeleriaJpaController(emf);
        GeneradorInforme.leerInformeBD(controller.findTablapapeleriaEntities());
    }//GEN-LAST:event_btnListarReporteActionPerformed

    //En caso de que el código no exista en la base de datos.
    private void ventanaNoExiste(String codigo){
        JOptionPane.showMessageDialog(rootPane, "El producto con el código "+codigo+" no existe.");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarBorrarProducto;
    private javax.swing.JButton btnBorrarBuscar;
    private javax.swing.JButton btnBorrarReset;
    private javax.swing.JButton btnBuscarBuscar;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnListarListar;
    private javax.swing.JButton btnListarProducto;
    private javax.swing.JButton btnListarReporte;
    private javax.swing.JButton btnModificarBuscar;
    private javax.swing.JButton btnModificarModificarProducto;
    private javax.swing.JButton btnModificarProducto;
    private javax.swing.JButton btnModificarReset;
    private javax.swing.JButton btnNuevoNuevoProducto;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnNuevoReset;
    private javax.swing.JFrame frmBorrarProducto;
    private javax.swing.JFrame frmBuscarProducto;
    private javax.swing.JFrame frmListarProducto;
    private javax.swing.JFrame frmModificarProducto;
    private javax.swing.JFrame frmNuevoProducto;
    private javax.swing.JLabel lblBorrarCodigo;
    private javax.swing.JLabel lblBorrarFamilia;
    private javax.swing.JLabel lblBorrarPrecio;
    private javax.swing.JLabel lblBorrarProducto;
    private javax.swing.JLabel lblBorrarRellena;
    private javax.swing.JLabel lblBuscarCodigo;
    private javax.swing.JLabel lblModificarCodigo;
    private javax.swing.JLabel lblModificarFamilia;
    private javax.swing.JLabel lblModificarPrecio;
    private javax.swing.JLabel lblModificarProducto;
    private javax.swing.JLabel lblModificarRellena;
    private javax.swing.JLabel lblNuevoCodigo;
    private javax.swing.JLabel lblNuevoFamilia;
    private javax.swing.JLabel lblNuevoPrecio;
    private javax.swing.JLabel lblNuevoProducto;
    private javax.swing.JLabel lblNuevoRellena;
    private javax.swing.JScrollPane scpBuscarTabla;
    private javax.swing.JScrollPane scpListarTabla;
    private javax.swing.JTable tblBuscarProductos;
    private javax.swing.JTable tblListarProductos;
    private javax.swing.JTextField txtBorrarCodigo;
    private javax.swing.JTextField txtBorrarFamilia;
    private javax.swing.JTextField txtBorrarPrecio;
    private javax.swing.JTextField txtBorrarProducto;
    private javax.swing.JTextField txtBuscarCodigo;
    private javax.swing.JTextField txtModificarCodigo;
    private javax.swing.JTextField txtModificarFamilia;
    private javax.swing.JTextField txtModificarPrecio;
    private javax.swing.JTextField txtModificarProducto;
    private javax.swing.JTextField txtNuevoCodigo;
    private javax.swing.JTextField txtNuevoFamilia;
    private javax.swing.JTextField txtNuevoPrecio;
    private javax.swing.JTextField txtNuevoProducto;
    // End of variables declaration//GEN-END:variables
}
